# backend/app/routes/intelligence.py

from fastapi import APIRouter, Query
from datetime import datetime, timezone

router = APIRouter(prefix="/api/intelligence", tags=["intelligence"])


@router.get("/feed")
async def intelligence_feed(limit: int = Query(40, ge=1, le=100)):
    """
    Returns intelligence feed items for the Football Intelligence page.
    Currently generates placeholder insights based on upcoming matches.
    """

    items = []

    for i in range(limit):
        items.append({
            "id": i,
            "type": "preview",
            "league": "Premier League",
            "title": f"Match insight #{i+1}",
            "summary": "Statistical preview generated by StatinSite model.",
            "created_at": datetime.now(timezone.utc).isoformat()
        })

    return {
        "mode": "preview",
        "count": len(items),
        "items": items
    }